djangostagram/urls.py
from django.contrib import admin
from django.urls import path, include

from duser.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("duser.urls", namespace="duser")),
    path("post/", include("post.urls", namespace="post")),
    path("", home),
]

duser/urls.py
from django.urls import path
from . import views

app_name = "duser"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("list/", views.post_list, name="post_list"),
    path("detail/<int:pk>", views.post_detail, name="post_detail"),
    path("upload/", views.post_upload, name="post_upload"),
]

duser/models.py
from django.db import models


class Duser(models.Model):
    userid = models.CharField(max_length=32, verbose_name="사용자아이디")
    useremail = models.EmailField(max_length=128, verbose_name="사용자이메일")
    password = models.CharField(max_length=64, verbose_name="비밀번호")
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name="가입일")

    def __str__(self):
        return self.userid + " " + self.useremail

    class Meta:
        db_table = "duser"
        verbose_name = "사용자"
        verbose_name_plural = verbose_name

post/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=128, verbose_name="제목")
    writer = models.ForeignKey(
        "duser.Duser", on_delete=models.CASCADE, verbose_name="작성자"
    )
    imagesrc = models.CharField(max_length=512, verbose_name="이미지주소")
    contents = models.TextField(verbose_name="내용")
    tags = models.ManyToManyField("tag.Tag", verbose_name="태그 ")
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name="작성일")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "post"
        verbose_name = "포스트"
        verbose_name_plural = verbose_name

tag/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=32, verbose_name="태그명")
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "tag"
        verbose_name = "태그"
        verbose_name_plural = verbose_name

duser/forms.py
from django import forms
from django.contrib.auth.hashers import check_password

from .models import Duser


class LoginForm(forms.Form):
    userid = forms.CharField(
        error_messages={"required": "아이디를 입력해 주세요."},
        max_length=32,
        label="사용자 이름",
    )
    password = forms.CharField(
        error_messages={"required": "비밀번호를 입력해 주세요."},
        widget=forms.PasswordInput,
        label="비밀번호",
    )

    def clean(self):
        cleaned_data = super().clean()

        userid = cleaned_data.get("userid")
        password = cleaned_data.get("password")

        if userid and password:
            try:
                duser = Duser.objects.get(userid=userid)
            except Duser.DoesNotExist:
                self.add_error("userid", "아이디가 없습니다.")
                return

            if not check_password(password, duser.password):
                self.add_error("password", "비밀번호가 틀렸습니다.")
            else:
                self.userid = userid
                self.id_pk = duser.id

post/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(
        error_messages={"required": "제목을 입력해 주세요."},
        max_length=128,
        label="제목",
    )
    imagesrc = forms.CharField(
        error_messages={"required": "이미지주소를 입력해 주세요."},
        max_length=128,
        label="이미지주소",
    )
    contents = forms.CharField(
        error_messages={"required": "내용을 입력해 주세요."},
        widget=forms.Textarea,
        label="내용",
    )
    tags = forms.CharField(required=False, label="태그")

duser/views.py
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect

from duser.forms import LoginForm
from duser.models import Duser


def home(request):
    # return HttpResponse("Home!")
    return redirect("/post/list")


def register(request):
    if request.method == "GET":
        return render(request, "register.html")

    elif request.method == "POST":
        userid = request.POST.get("userid", None)
        useremail = request.POST.get("useremail", None)
        password = request.POST.get("password", None)
        re_password = request.POST.get("re-password", None)

        res_data = {}
        if not (userid and useremail and password and re_password):
            res_data["error"] = "모든 값을 입력해야 합니다."

        elif password != re_password:
            res_data["error"] = "비밀번호가 다릅니다."

        else:
            try:
                duser = Duser.objects.get(userid=userid)
            except Duser.DoesNotExist:
                duser = Duser(
                    userid=userid, useremail=useremail, password=make_password(password)
                )
                duser.save()
                return redirect("/")
            else:
                res_data["error"] = "해당 아이디가 이미 존재합니다."

        return render(request, "register.html", res_data)


def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            # 세션
            request.session["user"] = form.id_pk
            request.session["userid"] = form.userid
            return redirect("/")
    else:
        form = LoginForm()

    return render(request, "login.html", {"form": form})


def logout(request):
    if request.session.get("user"):
        del request.session["user"]

    return redirect("/")

post/views.py
from django.core.paginator import Paginator
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect

from duser.models import Duser
from .forms import PostForm
from .models import Post
from tag.models import Tag


def post_upload(request):
    if not request.session.get("user"):
        return redirect("/user/login")

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            user = request.session.get("user")
            duser = Duser.objects.get(pk=user)

            post = Post()
            post.title = form.cleaned_data["title"]
            post.imagesrc = form.cleaned_data["imagesrc"]
            post.contents = form.cleaned_data["contents"]
            post.writer = duser
            post.save()

            tags = form.cleaned_data["tags"].split(",")
            for tag in tags:
                if not tag:
                    continue

                _tag, _ = Tag.objects.get_or_create(name=tag)
                post.tags.add(_tag)

            return redirect("/post/list/")

    else:
        form = PostForm()

    return render(request, "post_upload.html", {"form": form})


def post_list(request):
    all_posts = Post.objects.all().order_by("-registered_date")
    page = int(request.GET.get("p", 1))
    paginator = Paginator(all_posts, 4)

    posts = paginator.get_page(page)

    return render(request, "post_list.html", {"posts": posts})


def post_detail(request, pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404("게시글을 찾을 수 없습니다.")

    return render(request, "post_detail.html", {"post": post})

tag/views.py
from django.shortcuts import render

# Create your views here.

duser/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="/static/bootstrap2.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>

        <title>Post!</title>
</head>
<body>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% include "navbar.html" %}

<div class="container">
    {% block contents %}
    {% endblock %}
</div>


</body>
</html>

duser/templates/home.html
{% extends "base.html" %}

{% block contents %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>홈페이지</h1>

        </div>
    </div>
    <div class="row mt-5">
        {% if request.session.user %}
            <button type='button' class="btn btn-primary btn-lg btn-block" onclick="location.href='/fcuser/logout/'">
                로그아웃
            </button>
        {% else %}
            <button type='button' class="btn btn-primary btn-block col-6" onclick="location.href='/fcuser/login/'">로그인
            </button>
            <button type='button' class="btn btn-primary btn-block col-6" onclick="location.href='/fcuser/register/'">
                회원가입
            </button>
        {% endif %}
        <button type='button' class="btn btn-primary btn-block" onclick="location.href='/board/list/'">게시물 보기</button>
    </div>

{% endblock %}

duser/templates/login.html
{% extends "base.html" %}

{% block contents %}
<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>로그인</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action=".">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                           placeholder="{{ field.label }}" name="{{ field.name }}">
                </div>
            {% if field.errors %}
                <span style="color: red">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
</div>
{% endblock %}

duser/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">DjangoStagram</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">타임라인</a>
                </li>
                <li class="nav-item">
                    {% if request.session.user %}
                        <a class="nav-link" href="{% url 'duser:logout' %}">로그아웃</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'duser:register' %}" >회원가입</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if request.session.user %}
                        <a class="nav-link" href="{% url 'post:post_upload' %}">글작성</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'duser:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

duser/templates/register.html
{% extends "base.html" %}

{% block contents %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>회원가입</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            {{ error }}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <form method="POST" action=".">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="userid">사용자 아이디</label>
                    <input type="text" class="form-control" id="userid" placeholder="사용자 아이디" name="userid">
                </div>
                <div class="form-group  mb-3">
                    <label for="useremail">사용자 이메일</label>
                    <input type="email" class="form-control" id="useremail" placeholder="사용자 이메일" name="useremail">
                </div>
                <div class="form-group  mb-3">
                    <label for="password">비밀번호</label>
                    <input type="password" class="form-control" id="password" placeholder="비밀번호" name="password">
                </div>
                <div class="form-group  mb-3">
                    <label for="re-password">비밀번호 확인</label>
                    <input type="password" class="form-control" id="re-password" placeholder="비밀번호 확인" name="re-password">
                </div>
                <button type="submit" class="btn btn-primary mb-3">등록</button>
            </form>
        </div>
    </div>
{% endblock %}

post/templates/post_detail.html
{% extends "base.html" %}

{% block contents %}
    <div class="row mt-3">
        <div class="col-12">
            <div class="card mb-3">
                <h3 class="card-header">{{ post.title }}</h3>
                <div class="card-body">
                    <h5 class="card-title">{{ post.tags.all|join:", " }}</h5>
                    <h6 class="card-subtitle text-muted">{{ post.writer }}</h6>
                </div>
                <img src="{{ post.imagesrc }}" alt="">
                <div class="card-body">
                    <p class="card-text">{{ post.contents|linebreaksbr  }}</p>
                </div>
                <div class="card-footer text-muted">
                    {{ post.registered_date }}
                </div>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary" onclick="location.href='/post/list/'">돌아가기</button>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post_list.html
{% extends "base.html" %}

{% block contents %}

    {% if request.session.user %}
        <div class="alert alert-dismissible alert-primary mt-3">
            <h4 class="alert-heading">Hello, {{ request.session.userid }}</h4>
        </div>
    {% endif %}


    {% for post in posts %}
        <div class="card mt-3" style="cursor:pointer" onclick="location.href='/post/detail/{{ post.id }}'">
            <h3 class="card-header">{{ post.title }}</h3>
            <div class="card-body">
                <h5 class="card-title">{{ post.tags.all|join:", " }}</h5>
                <h6 class="card-subtitle text-muted">{{ post.writer }}</h6>
            </div>
            <img src="{{ post.imagesrc }}" alt="">
            <div class="card-body">
                <p class="card-text">{{ post.contents|truncatewords:40  }}</p>
            </div>
            <div class="card-footer text-muted">
                {{ post.registered_date }}
            </div>
        </div>

    {% endfor %}


        <div class="row my-3">
            <div class="col-12">
                <ul class="pagination justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a href="?p={{ posts.previous_page_number }}" class="page-link">이전으로</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link">이전으로</a>
                        </li>
                    {% endif %}

                    <li class="page-item active">
                        <a href="#" class="page-link">{{ posts.number }} / {{ posts.paginator.num_pages }}</a>
                    </li>

                    {% if posts.has_next %}
                        <li class="page-item">
                            <a href="?p={{ posts.next_page_number }}" class="page-link">다음으로</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link ">다음으로</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post_upload.html
{% extends "base.html" %}

{% block contents %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>글작성</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <form method="POST" action=".">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group p-3">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% ifequal field.name 'contents' %}
                            <textarea class="form-control"
                                      name="{{ field.name }}"
                                      id=""
                                      placeholder="{{ field.label }}"
                                      rows="10"></textarea>
                        {% else %}

                            <input type="{{ field.field.widget.input_type }}" class="form-control"
                                   id="{{ field.id_for_label }}"
                                   placeholder="{{ field.label }}" name="{{ field.name }}">
                        {% endifequal %}
                    </div>
                    {% if field.errors %}
                        <span style="color: red">{{ field.errors }}</span>
                    {% endif %}
                {% endfor %}
                <div class="p-3">
                    <button type="submit" class="btn btn-primary">글쓰기</button>
                    <button type='button' class="btn btn-primary" onclick="location.href='/post/list/'">돌아가기</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}